#START
Run=330
inputFile=/home-pbs/vcherepa/cms_work/BeamTest/CMSSW_9_2_3/src/Ntuples/AnalysisTree_000330.root
outputFile=Hits330.root
doTelescopeMatching=1
doChannelMasking_=0
channelMaskFile=chmask.txt
residualSigmaDUT=0.026
maximumEVT=200000
nStrips=254
pitchDUT=0.09
geomFile=geometryFnal.json
#only needed by Alignment Analysis
isProductionmode=0
alignmentOutputFile=alignmentparOutput_000330.json
#For analysis with track match
readAlignmentFromfile=1
#END
